name: Convert Markdown to PDF

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the action

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Pandoc
        run: |
          choco install pandoc -y  # Use Chocolatey package manager for Pandoc installation on Windows

      - name: Convert Markdown to PDF
        run: pandoc -o output.pdf practice-exam-1.md
